PyPI:
  requests: psf/requests
  rich: Textualize/rich
  click: pallets/click
  oss-trust-framework: chrisgillham/oss-trust-framework
  httpx: encode/httpx
  pyyaml: yaml/pyyaml
  pydantic: pydantic/pydantic
  pyotp: pyotp/pyotp
  cryptography: cryptography/cryptography
npm: {}
Cargo: {}
require_attestation:
  PyPI:
  - requests
  - httpx
  - pyyaml
  - pydantic
  - pyotp
  - cryptography
